// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _Zevenseg_HH_
#define _Zevenseg_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct Zevenseg : public sc_module {
    // Port declarations 11
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_logic > sw;
    sc_out< sc_lv<4> > led_V;
    sc_out< sc_logic > led_V_ap_vld;
    sc_out< sc_lv<7> > display_V;
    sc_out< sc_logic > display_V_ap_vld;


    // Module declarations
    Zevenseg(sc_module_name name);
    SC_HAS_PROCESS(Zevenseg);

    ~Zevenseg();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    sc_signal< sc_lv<4> > ap_CS_fsm;
    sc_signal< sc_lv<1> > ap_CS_fsm_state1;
    sc_signal< sc_lv<32> > value_r;
    sc_signal< sc_lv<32> > value_assign_fu_207_p3;
    sc_signal< sc_lv<32> > value_assign_reg_464;
    sc_signal< sc_lv<4> > tmp_5_fu_221_p1;
    sc_signal< sc_lv<4> > tmp_5_reg_483;
    sc_signal< sc_lv<7> > tmp_21_i_fu_358_p3;
    sc_signal< sc_lv<7> > tmp_21_i_reg_488;
    sc_signal< sc_lv<1> > ap_CS_fsm_state2;
    sc_signal< sc_lv<1> > tmp_22_i_fu_366_p2;
    sc_signal< sc_lv<1> > tmp_22_i_reg_493;
    sc_signal< sc_lv<1> > tmp_23_i_fu_371_p2;
    sc_signal< sc_lv<1> > tmp_23_i_reg_498;
    sc_signal< sc_lv<1> > tmp_27_i_fu_376_p2;
    sc_signal< sc_lv<1> > tmp_27_i_reg_504;
    sc_signal< sc_lv<1> > tmp_28_i_fu_381_p2;
    sc_signal< sc_lv<1> > tmp_28_i_reg_509;
    sc_signal< sc_lv<1> > tmp_32_i_fu_386_p2;
    sc_signal< sc_lv<1> > tmp_32_i_reg_515;
    sc_signal< sc_lv<1> > tmp_33_i_fu_391_p2;
    sc_signal< sc_lv<1> > tmp_33_i_reg_520;
    sc_signal< sc_lv<7> > value_display_i_fu_444_p3;
    sc_signal< sc_lv<7> > value_display_i_reg_526;
    sc_signal< sc_lv<1> > ap_CS_fsm_state3;
    sc_signal< sc_lv<27> > i_1_fu_458_p2;
    sc_signal< sc_lv<1> > ap_CS_fsm_state4;
    sc_signal< sc_lv<27> > i_reg_126;
    sc_signal< sc_lv<1> > exitcond_fu_452_p2;
    sc_signal< sc_lv<32> > tmp_fu_141_p2;
    sc_signal< sc_lv<28> > tmp_1_fu_147_p4;
    sc_signal< sc_lv<1> > icmp_fu_157_p2;
    sc_signal< sc_lv<31> > tmp_3_fu_171_p1;
    sc_signal< sc_lv<32> > tmp_2_fu_175_p2;
    sc_signal< sc_lv<1> > tmp_4_fu_187_p3;
    sc_signal< sc_lv<31> > tmp_2_cast_fu_181_p2;
    sc_signal< sc_lv<31> > p_1_fu_195_p3;
    sc_signal< sc_lv<1> > value_assign_fu_207_p0;
    sc_signal< sc_lv<32> > p_s_fu_163_p3;
    sc_signal< sc_lv<32> > p_1_cast_fu_203_p1;
    sc_signal< sc_lv<1> > tmp_i_fu_225_p2;
    sc_signal< sc_lv<1> > tmp_3_i_fu_243_p2;
    sc_signal< sc_lv<1> > tmp_2_i_fu_238_p2;
    sc_signal< sc_lv<1> > tmp_5_i_fu_256_p2;
    sc_signal< sc_lv<7> > tmp_4_i_fu_248_p3;
    sc_signal< sc_lv<7> > tmp_1_i_fu_230_p3;
    sc_signal< sc_lv<1> > tmp_8_i_fu_275_p2;
    sc_signal< sc_lv<1> > tmp_7_i_fu_270_p2;
    sc_signal< sc_lv<1> > tmp_10_i_fu_288_p2;
    sc_signal< sc_lv<7> > tmp_9_i_cast_cast_fu_280_p3;
    sc_signal< sc_lv<7> > tmp_6_i_fu_262_p3;
    sc_signal< sc_lv<1> > tmp_13_i_fu_307_p2;
    sc_signal< sc_lv<1> > tmp_12_i_fu_302_p2;
    sc_signal< sc_lv<1> > tmp_15_i_fu_320_p2;
    sc_signal< sc_lv<7> > tmp_14_i_cast_cast_fu_312_p3;
    sc_signal< sc_lv<7> > tmp_11_i_fu_294_p3;
    sc_signal< sc_lv<1> > tmp_18_i_fu_339_p2;
    sc_signal< sc_lv<1> > tmp_17_i_fu_334_p2;
    sc_signal< sc_lv<1> > tmp_20_i_fu_352_p2;
    sc_signal< sc_lv<7> > tmp_19_i_cast_cast_fu_344_p3;
    sc_signal< sc_lv<7> > tmp_16_i_fu_326_p3;
    sc_signal< sc_lv<1> > tmp_25_i_fu_403_p2;
    sc_signal< sc_lv<7> > tmp_24_i_cast_cast_fu_396_p3;
    sc_signal< sc_lv<1> > tmp_30_i_fu_421_p2;
    sc_signal< sc_lv<7> > tmp_29_i_fu_414_p3;
    sc_signal< sc_lv<7> > tmp_26_i_fu_407_p3;
    sc_signal< sc_lv<1> > tmp_35_i_fu_440_p2;
    sc_signal< sc_lv<7> > tmp_34_i_cast_cast_fu_433_p3;
    sc_signal< sc_lv<7> > tmp_31_i_fu_425_p3;
    sc_signal< sc_lv<4> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<4> ap_ST_fsm_state1;
    static const sc_lv<4> ap_ST_fsm_state2;
    static const sc_lv<4> ap_ST_fsm_state3;
    static const sc_lv<4> ap_ST_fsm_state4;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<27> ap_const_lv27_0;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_1F;
    static const sc_lv<28> ap_const_lv28_0;
    static const sc_lv<32> ap_const_lv32_FFFFFFFF;
    static const sc_lv<31> ap_const_lv31_7FFFFFFF;
    static const sc_lv<31> ap_const_lv31_F;
    static const sc_lv<7> ap_const_lv7_40;
    static const sc_lv<7> ap_const_lv7_0;
    static const sc_lv<7> ap_const_lv7_24;
    static const sc_lv<7> ap_const_lv7_79;
    static const sc_lv<7> ap_const_lv7_19;
    static const sc_lv<7> ap_const_lv7_30;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<7> ap_const_lv7_2;
    static const sc_lv<7> ap_const_lv7_12;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<32> ap_const_lv32_F;
    static const sc_lv<7> ap_const_lv7_E;
    static const sc_lv<7> ap_const_lv7_78;
    static const sc_lv<32> ap_const_lv32_9;
    static const sc_lv<32> ap_const_lv32_A;
    static const sc_lv<32> ap_const_lv32_B;
    static const sc_lv<32> ap_const_lv32_C;
    static const sc_lv<32> ap_const_lv32_D;
    static const sc_lv<32> ap_const_lv32_E;
    static const sc_lv<7> ap_const_lv7_8;
    static const sc_lv<7> ap_const_lv7_10;
    static const sc_lv<7> ap_const_lv7_46;
    static const sc_lv<7> ap_const_lv7_3;
    static const sc_lv<7> ap_const_lv7_6;
    static const sc_lv<7> ap_const_lv7_21;
    static const sc_lv<27> ap_const_lv27_5F5E100;
    static const sc_lv<27> ap_const_lv27_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_display_V();
    void thread_display_V_ap_vld();
    void thread_exitcond_fu_452_p2();
    void thread_i_1_fu_458_p2();
    void thread_icmp_fu_157_p2();
    void thread_led_V();
    void thread_led_V_ap_vld();
    void thread_p_1_cast_fu_203_p1();
    void thread_p_1_fu_195_p3();
    void thread_p_s_fu_163_p3();
    void thread_tmp_10_i_fu_288_p2();
    void thread_tmp_11_i_fu_294_p3();
    void thread_tmp_12_i_fu_302_p2();
    void thread_tmp_13_i_fu_307_p2();
    void thread_tmp_14_i_cast_cast_fu_312_p3();
    void thread_tmp_15_i_fu_320_p2();
    void thread_tmp_16_i_fu_326_p3();
    void thread_tmp_17_i_fu_334_p2();
    void thread_tmp_18_i_fu_339_p2();
    void thread_tmp_19_i_cast_cast_fu_344_p3();
    void thread_tmp_1_fu_147_p4();
    void thread_tmp_1_i_fu_230_p3();
    void thread_tmp_20_i_fu_352_p2();
    void thread_tmp_21_i_fu_358_p3();
    void thread_tmp_22_i_fu_366_p2();
    void thread_tmp_23_i_fu_371_p2();
    void thread_tmp_24_i_cast_cast_fu_396_p3();
    void thread_tmp_25_i_fu_403_p2();
    void thread_tmp_26_i_fu_407_p3();
    void thread_tmp_27_i_fu_376_p2();
    void thread_tmp_28_i_fu_381_p2();
    void thread_tmp_29_i_fu_414_p3();
    void thread_tmp_2_cast_fu_181_p2();
    void thread_tmp_2_fu_175_p2();
    void thread_tmp_2_i_fu_238_p2();
    void thread_tmp_30_i_fu_421_p2();
    void thread_tmp_31_i_fu_425_p3();
    void thread_tmp_32_i_fu_386_p2();
    void thread_tmp_33_i_fu_391_p2();
    void thread_tmp_34_i_cast_cast_fu_433_p3();
    void thread_tmp_35_i_fu_440_p2();
    void thread_tmp_3_fu_171_p1();
    void thread_tmp_3_i_fu_243_p2();
    void thread_tmp_4_fu_187_p3();
    void thread_tmp_4_i_fu_248_p3();
    void thread_tmp_5_fu_221_p1();
    void thread_tmp_5_i_fu_256_p2();
    void thread_tmp_6_i_fu_262_p3();
    void thread_tmp_7_i_fu_270_p2();
    void thread_tmp_8_i_fu_275_p2();
    void thread_tmp_9_i_cast_cast_fu_280_p3();
    void thread_tmp_fu_141_p2();
    void thread_tmp_i_fu_225_p2();
    void thread_value_assign_fu_207_p0();
    void thread_value_assign_fu_207_p3();
    void thread_value_display_i_fu_444_p3();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
