// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// ==============================================================

#define AP_INT_MAX_W 32678

#include <systemc>
#include <iostream>
#include <cstdlib>
#include <cstddef>
#include <stdint.h>
#include "SysCFileHandler.h"
#include "ap_int.h"
#include "ap_fixed.h"
#include <complex>
#include <stdbool.h>
#include "autopilot_cbe.h"
#include "ap_stream.h"
#include "hls_stream.h"
#include "hls_half.h"
#include "hls_signal_handler.h"

using namespace std;
using namespace sc_core;
using namespace sc_dt;


// [dump_struct_tree [build_nameSpaceTree] dumpedStructList] ---------->


// [dump_enumeration [get_enumeration_list]] ---------->


// wrapc file define: "sw"
#define AUTOTB_TVIN_sw  "../tv/cdatafile/c.Zevenseg.autotvin_sw.dat"
// wrapc file define: "led_V"
#define AUTOTB_TVOUT_led_V  "../tv/cdatafile/c.Zevenseg.autotvout_led_V.dat"
// wrapc file define: "display_V"
#define AUTOTB_TVOUT_display_V  "../tv/cdatafile/c.Zevenseg.autotvout_display_V.dat"

#define INTER_TCL  "../tv/cdatafile/ref.tcl"

// tvout file define: "led_V"
#define AUTOTB_TVOUT_PC_led_V  "../tv/rtldatafile/rtl.Zevenseg.autotvout_led_V.dat"
// tvout file define: "display_V"
#define AUTOTB_TVOUT_PC_display_V  "../tv/rtldatafile/rtl.Zevenseg.autotvout_display_V.dat"

class INTER_TCL_FILE {
	public:
		INTER_TCL_FILE(const char* name) {
			mName = name;
			sw_depth = 0;
			led_V_depth = 0;
			display_V_depth = 0;
			trans_num =0;
		}

		~INTER_TCL_FILE() {
			mFile.open(mName);
			if (!mFile.good()) {
				cout << "Failed to open file ref.tcl" << endl;
				exit (1);
			}
			string total_list = get_depth_list();
			mFile << "set depth_list {\n";
			mFile << total_list;
			mFile << "}\n";
			mFile << "set trans_num "<<trans_num<<endl;
			mFile.close();
		}

		string get_depth_list () {
			stringstream total_list;
			total_list << "{sw " << sw_depth << "}\n";
			total_list << "{led_V " << led_V_depth << "}\n";
			total_list << "{display_V " << display_V_depth << "}\n";
			return total_list.str();
		}

		void set_num (int num , int* class_num) {
			(*class_num) = (*class_num) > num ? (*class_num) : num;
		}
	public:
		int sw_depth;
		int led_V_depth;
		int display_V_depth;
		int trans_num;

	private:
		ofstream mFile;
		const char* mName;
};

extern void Zevenseg (
bool sw,
ap_uint<4>* led,
ap_uint<7>* display);

void AESL_WRAP_Zevenseg (
bool sw,
ap_uint<4>* led,
ap_uint<7>* display)
{
	refine_signal_handler();
	fstream wrapc_switch_file_token;
	wrapc_switch_file_token.open(".hls_cosim_wrapc_switch.log");
	int AESL_i;
	if (wrapc_switch_file_token.good())
	{
		CodeState = ENTER_WRAPC_PC;
		static unsigned AESL_transaction_pc = 0;
		string AESL_token;
		string AESL_num;
		static AESL_FILE_HANDLER aesl_fh;


		// output port post check: "led_V"
		aesl_fh.read(AUTOTB_TVOUT_PC_led_V, AESL_token); // [[transaction]]
		if (AESL_token != "[[transaction]]")
		{
			exit(1);
		}
		aesl_fh.read(AUTOTB_TVOUT_PC_led_V, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(AUTOTB_TVOUT_PC_led_V, AESL_token); // data

			sc_bv<4> *led_V_pc_buffer = new sc_bv<4>[1];
			int i = 0;

			while (AESL_token != "[[/transaction]]")
			{
				bool no_x = false;
				bool err = false;

				// search and replace 'X' with "0" from the 1st char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('X');
					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'led_V', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				no_x = false;

				// search and replace 'x' with "0" from the 3rd char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('x', 2);

					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'led_V', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				// push token into output port buffer
				if (AESL_token != "")
				{
					led_V_pc_buffer[i] = AESL_token.c_str();
					i++;
				}

				aesl_fh.read(AUTOTB_TVOUT_PC_led_V, AESL_token); // data or [[/transaction]]

				if (AESL_token == "[[[/runtime]]]" || aesl_fh.eof(AUTOTB_TVOUT_PC_led_V))
				{
					exit(1);
				}
			}

			// ***********************************
			if (i > 0)
			{
				// RTL Name: led_V
				{
					// bitslice(3, 0)
					// {
						// celement: led.V(3, 0)
						// {
							sc_lv<4>* led_V_lv0_0_0_1 = new sc_lv<4>[1];
						// }
					// }

					// bitslice(3, 0)
					{
						int hls_map_index = 0;
						// celement: led.V(3, 0)
						{
							// carray: (0) => (0) @ (1)
							for (int i_0 = 0; i_0 <= 0; i_0 += 1)
							{
								if (&(led[0]) != NULL) // check the null address if the c port is array or others
								{
									led_V_lv0_0_0_1[hls_map_index++].range(3, 0) = sc_bv<4>(led_V_pc_buffer[hls_map_index].range(3, 0));
								}
							}
						}
					}

					// bitslice(3, 0)
					{
						int hls_map_index = 0;
						// celement: led.V(3, 0)
						{
							// carray: (0) => (0) @ (1)
							for (int i_0 = 0; i_0 <= 0; i_0 += 1)
							{
								// sub                    : i_0
								// ori_name               : led[i_0]
								// sub_1st_elem           : 0
								// ori_name_1st_elem      : led[0]
								// output_left_conversion : led[i_0]
								// output_type_conversion : (led_V_lv0_0_0_1[hls_map_index++]).to_string(SC_BIN).c_str()
								if (&(led[0]) != NULL) // check the null address if the c port is array or others
								{
									led[i_0] = (led_V_lv0_0_0_1[hls_map_index++]).to_string(SC_BIN).c_str();
								}
							}
						}
					}
				}
			}

			// release memory allocation
			delete [] led_V_pc_buffer;
		}

		// output port post check: "display_V"
		aesl_fh.read(AUTOTB_TVOUT_PC_display_V, AESL_token); // [[transaction]]
		if (AESL_token != "[[transaction]]")
		{
			exit(1);
		}
		aesl_fh.read(AUTOTB_TVOUT_PC_display_V, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(AUTOTB_TVOUT_PC_display_V, AESL_token); // data

			sc_bv<7> *display_V_pc_buffer = new sc_bv<7>[1];
			int i = 0;

			while (AESL_token != "[[/transaction]]")
			{
				bool no_x = false;
				bool err = false;

				// search and replace 'X' with "0" from the 1st char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('X');
					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'display_V', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				no_x = false;

				// search and replace 'x' with "0" from the 3rd char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('x', 2);

					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'display_V', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				// push token into output port buffer
				if (AESL_token != "")
				{
					display_V_pc_buffer[i] = AESL_token.c_str();
					i++;
				}

				aesl_fh.read(AUTOTB_TVOUT_PC_display_V, AESL_token); // data or [[/transaction]]

				if (AESL_token == "[[[/runtime]]]" || aesl_fh.eof(AUTOTB_TVOUT_PC_display_V))
				{
					exit(1);
				}
			}

			// ***********************************
			if (i > 0)
			{
				// RTL Name: display_V
				{
					// bitslice(6, 0)
					// {
						// celement: display.V(6, 0)
						// {
							sc_lv<7>* display_V_lv0_0_0_1 = new sc_lv<7>[1];
						// }
					// }

					// bitslice(6, 0)
					{
						int hls_map_index = 0;
						// celement: display.V(6, 0)
						{
							// carray: (0) => (0) @ (1)
							for (int i_0 = 0; i_0 <= 0; i_0 += 1)
							{
								if (&(display[0]) != NULL) // check the null address if the c port is array or others
								{
									display_V_lv0_0_0_1[hls_map_index++].range(6, 0) = sc_bv<7>(display_V_pc_buffer[hls_map_index].range(6, 0));
								}
							}
						}
					}

					// bitslice(6, 0)
					{
						int hls_map_index = 0;
						// celement: display.V(6, 0)
						{
							// carray: (0) => (0) @ (1)
							for (int i_0 = 0; i_0 <= 0; i_0 += 1)
							{
								// sub                    : i_0
								// ori_name               : display[i_0]
								// sub_1st_elem           : 0
								// ori_name_1st_elem      : display[0]
								// output_left_conversion : display[i_0]
								// output_type_conversion : (display_V_lv0_0_0_1[hls_map_index++]).to_string(SC_BIN).c_str()
								if (&(display[0]) != NULL) // check the null address if the c port is array or others
								{
									display[i_0] = (display_V_lv0_0_0_1[hls_map_index++]).to_string(SC_BIN).c_str();
								}
							}
						}
					}
				}
			}

			// release memory allocation
			delete [] display_V_pc_buffer;
		}

		AESL_transaction_pc++;
	}
	else
	{
		CodeState = ENTER_WRAPC;
		static unsigned AESL_transaction;

		static AESL_FILE_HANDLER aesl_fh;

		// "sw"
		char* tvin_sw = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_sw);

		// "led_V"
		char* tvout_led_V = new char[50];
		aesl_fh.touch(AUTOTB_TVOUT_led_V);

		// "display_V"
		char* tvout_display_V = new char[50];
		aesl_fh.touch(AUTOTB_TVOUT_display_V);

		CodeState = DUMP_INPUTS;
		static INTER_TCL_FILE tcl_file(INTER_TCL);
		int leading_zero;

		// [[transaction]]
		sprintf(tvin_sw, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_sw, tvin_sw);

		sc_bv<1> sw_tvin_wrapc_buffer;

		// RTL Name: sw
		{
			// bitslice(0, 0)
			{
				// celement: sw(0, 0)
				{
					// carray: (0) => (0) @ (0)
					{
						// sub                   : 
						// ori_name              : sw
						// sub_1st_elem          : 
						// ori_name_1st_elem     : sw
						// regulate_c_name       : sw
						// input_type_conversion : sw
						if (&(sw) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<1> sw_tmp_mem;
							sw_tmp_mem = sw;
							sw_tvin_wrapc_buffer.range(0, 0) = sw_tmp_mem.range(0, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvin_sw, "%s\n", (sw_tvin_wrapc_buffer).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_sw, tvin_sw);
		}

		tcl_file.set_num(1, &tcl_file.sw_depth);
		sprintf(tvin_sw, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_sw, tvin_sw);

// [call_c_dut] ---------->

		CodeState = CALL_C_DUT;
		Zevenseg(sw, led, display);

		CodeState = DUMP_OUTPUTS;

		// [[transaction]]
		sprintf(tvout_led_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVOUT_led_V, tvout_led_V);

		sc_bv<4>* led_V_tvout_wrapc_buffer = new sc_bv<4>[1];

		// RTL Name: led_V
		{
			// bitslice(3, 0)
			{
				int hls_map_index = 0;
				// celement: led.V(3, 0)
				{
					// carray: (0) => (0) @ (1)
					for (int i_0 = 0; i_0 <= 0; i_0 += 1)
					{
						// sub                   : i_0
						// ori_name              : led[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : led[0]
						// regulate_c_name       : led_V
						// input_type_conversion : (led[i_0]).to_string(2).c_str()
						if (&(led[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<4> led_V_tmp_mem;
							led_V_tmp_mem = (led[i_0]).to_string(2).c_str();
							led_V_tvout_wrapc_buffer[hls_map_index++].range(3, 0) = led_V_tmp_mem.range(3, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvout_led_V, "%s\n", (led_V_tvout_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVOUT_led_V, tvout_led_V);
		}

		tcl_file.set_num(1, &tcl_file.led_V_depth);
		sprintf(tvout_led_V, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVOUT_led_V, tvout_led_V);

		// release memory allocation
		delete [] led_V_tvout_wrapc_buffer;

		// [[transaction]]
		sprintf(tvout_display_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVOUT_display_V, tvout_display_V);

		sc_bv<7>* display_V_tvout_wrapc_buffer = new sc_bv<7>[1];

		// RTL Name: display_V
		{
			// bitslice(6, 0)
			{
				int hls_map_index = 0;
				// celement: display.V(6, 0)
				{
					// carray: (0) => (0) @ (1)
					for (int i_0 = 0; i_0 <= 0; i_0 += 1)
					{
						// sub                   : i_0
						// ori_name              : display[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : display[0]
						// regulate_c_name       : display_V
						// input_type_conversion : (display[i_0]).to_string(2).c_str()
						if (&(display[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<7> display_V_tmp_mem;
							display_V_tmp_mem = (display[i_0]).to_string(2).c_str();
							display_V_tvout_wrapc_buffer[hls_map_index++].range(6, 0) = display_V_tmp_mem.range(6, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvout_display_V, "%s\n", (display_V_tvout_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVOUT_display_V, tvout_display_V);
		}

		tcl_file.set_num(1, &tcl_file.display_V_depth);
		sprintf(tvout_display_V, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVOUT_display_V, tvout_display_V);

		// release memory allocation
		delete [] display_V_tvout_wrapc_buffer;

		CodeState = DELETE_CHAR_BUFFERS;
		// release memory allocation: "sw"
		delete [] tvin_sw;
		// release memory allocation: "led_V"
		delete [] tvout_led_V;
		// release memory allocation: "display_V"
		delete [] tvout_display_V;

		AESL_transaction++;

		tcl_file.set_num(AESL_transaction , &tcl_file.trans_num);
	}
}

